package br.com.fiap.phase4.commons.test.architecture;

import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaConstructor;
import com.tngtech.archunit.core.domain.JavaModifier;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchCondition;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.lang.ConditionEvents;
import com.tngtech.archunit.lang.SimpleConditionEvent;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RestController;

import static com.tngtech.archunit.core.domain.JavaClass.Predicates.resideInAPackage;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.fields;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noFields;

/**
 * Reusable architectural rules enforced across all Phase 4 microservices.
 */
public final class CommonArchitectureRules {

    private CommonArchitectureRules() {
    }

    @ArchTest
    public static final ArchRule domainMustNotDependOnSpringWebOrData =
            noClasses().that().resideInAPackage("..domain..")
                    .should().dependOnClassesThat().resideInAnyPackage(
                            "org.springframework.web..",
                            "org.springframework.data..",
                            "org.springframework.kafka.."
                    )
                    .because("Hexagonal domain model and use cases must not depend on Spring Web, Spring Data, or Spring Kafka infrastructure");

    @ArchTest
    public static final ArchRule domainMustNotDependOnAdapters =
            noClasses().that().resideInAPackage("..domain..")
                    .should().dependOnClassesThat().resideInAPackage("..adapter..")
                    .because("Hexagonal domain layer must not depend on adapters layer");

    @ArchTest
    public static final ArchRule controllersMustImplementOpenApiGeneratedInterface =
            classes()
                    .that().areAnnotatedWith(RestController.class)
                    .should().implement(resideInAPackage("..adapter.in.web.api.."))
                    .because("All REST controllers must implement an OpenAPI-generated interface from the api package to guarantee API-first contract conformity");

    @ArchTest
    public static final ArchRule noFieldInjection =
            noFields()
                    .should().beAnnotatedWith("org.springframework.beans.factory.annotation.Autowired")
                    .because("Field injection is prohibited; use Lombok's @RequiredArgsConstructor for constructor injection");

    @ArchTest
    public static final ArchRule springComponentsMustUseLombokForConstructorInjection =
            classes()
                    .that().areAnnotatedWith(RestController.class)
                    .or().areAnnotatedWith(Service.class)
                    .or().areAnnotatedWith(Component.class)
                    .and().doNotHaveModifier(JavaModifier.ABSTRACT)
                    .should(new ArchCondition<>("use Lombok @RequiredArgsConstructor for constructor injection") {
                        @Override
                        public void check(JavaClass javaClass, ConditionEvents events) {
                            for (JavaConstructor constructor : javaClass.getConstructors()) {
                                if (!constructor.getRawParameterTypes().isEmpty() && !constructor.isAnnotatedWith("lombok.Generated")) {
                                    events.add(SimpleConditionEvent.violated(constructor,
                                            String.format("Constructor %s in class %s is not generated by Lombok. Use @RequiredArgsConstructor or other Lombok annotations instead.",
                                                    constructor.getDescription(), javaClass.getName())));
                                }
                            }
                        }
                    })
                    .because("All dependency injection in Spring components (@RestController, @Service, @Component) must use Lombok generated constructors (@RequiredArgsConstructor)");

    @ArchTest
    public static final ArchRule loggersMustBeGeneratedByLombok =
            fields()
                    .that().haveRawType("org.slf4j.Logger")
                    .should().beAnnotatedWith("lombok.Generated")
                    .because("Loggers must be generated by Lombok's @Slf4j annotation rather than manually instantiated with LoggerFactory");
}
